version: 2
updates:
  # Обновления для npm (Node.js) зависимостей
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "npm"
  
  # Обновления для npm в каждой директории frontend
  - package-ecosystem: "npm"
    directory: "/auth/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "npm"
      - "auth"
  
  - package-ecosystem: "npm"
    directory: "/application/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "npm"
      - "application"
  
  - package-ecosystem: "npm"
    directory: "/admin/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "npm"
      - "admin"
  
  # Обновления для Python (pip) зависимостей
  - package-ecosystem: "pip"
    directory: "/auth/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "python"
      - "auth"
  
  - package-ecosystem: "pip"
    directory: "/application/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "python"
      - "application"
  
  - package-ecosystem: "pip"
    directory: "/admin/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "python"
      - "admin"
  
  # Обновления для Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
  
  # Обновления для Docker в каждой директории
  - package-ecosystem: "docker"
    directory: "/auth/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "auth"
  
  - package-ecosystem: "docker"
    directory: "/application/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "application"
  
  - package-ecosystem: "docker"
    directory: "/admin/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "admin"
  
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "docker"
      - "nginx"
  
  # Обновления для GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    labels:
      - "dependencies"
      - "github-actions"



# Глобальная настройка переменных окружения для всех задач, включая обязательный пароль для PostgreSQL
env:
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "yoga_db" 