global:
  resolve_timeout: 5m
  telegram_api_url: 'https://api.telegram.org'

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'telegram-notifications'
  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
      group_wait: 10s
      repeat_interval: 1h

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '{{ secrets.TELEGRAM_TOKEN }}'
        chat_id: '{{ secrets.TELEGRAM_TO }}'
        parse_mode: 'HTML'
        message: |
          ⚠️ <b>{{ .Status | toUpper }}</b> {{ if eq .Status "firing" }}🔥{{ end }}
          <b>{{ .CommonLabels.alertname }}</b>
          {{ range .Alerts -}}
          <b>Описание:</b> {{ .Annotations.description }}
          <b>Начало:</b> {{ .StartsAt.Format "02.01.2006 15:04:05" }}
          {{ if ne .Status "firing" -}}
          <b>Окончание:</b> {{ .EndsAt.Format "02.01.2006 15:04:05" }}
          {{- end }}
          {{ end }}

  - name: 'telegram-critical'
    telegram_configs:
      - bot_token: '{{ secrets.TELEGRAM_TOKEN }}'
        chat_id: '{{ secrets.TELEGRAM_TO }}'
        parse_mode: 'HTML'
        message: |
          🚨 <b>КРИТИЧЕСКАЯ ОШИБКА!</b> 🚨
          <b>{{ .CommonLabels.alertname }}</b>
          {{ range .Alerts -}}
          <b>Описание:</b> {{ .Annotations.description }}
          <b>Начало:</b> {{ .StartsAt.Format "02.01.2006 15:04:05" }}
          {{ if ne .Status "firing" -}}
          <b>Окончание:</b> {{ .EndsAt.Format "02.01.2006 15:04:05" }}
          {{- end }}
          {{ end }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'job'] 