version: 2
updates:
  # Python зависимости для бэкенда
  - package-ecosystem: "pip"
    directory: "/admin/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "python"
  
  - package-ecosystem: "pip"
    directory: "/application/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "python"
  
  - package-ecosystem: "pip"
    directory: "/auth/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "python"
  
  # npm зависимости для фронтенда
  - package-ecosystem: "npm"
    directory: "/admin/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "javascript"
  
  - package-ecosystem: "npm"
    directory: "/application/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "javascript"
  
  - package-ecosystem: "npm"
    directory: "/auth/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "javascript"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    auto-merge: false 
    labels:
      - "dependencies"
      - "github-actions"
  
  # Docker зависимости
  - package-ecosystem: "docker"
    directory: "/admin/backend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker"
  
  - package-ecosystem: "docker"
    directory: "/application/backend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker"
  
  - package-ecosystem: "docker"
    directory: "/auth/backend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker"
  
  - package-ecosystem: "docker"
    directory: "/admin/frontend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker"
  
  - package-ecosystem: "docker"
    directory: "/application/frontend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker"
  
  - package-ecosystem: "docker"
    directory: "/auth/frontend"
    schedule:
      interval: "monthly"
      open-pull-requests-limit: 2
    auto-merge: false
    labels:
      - "dependencies"
      - "docker" 