apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "30s"
      httpMethod: "POST"

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "[yoga-backend-]YYYY.MM.DD,[yoga-frontend-]YYYY.MM.DD,[fluentd-]YYYY.MM.DD"
    jsonData:
      timeField: "@timestamp"
      interval: "Daily"
      logMessageField: "message"
      logLevelField: "level"
      dataLinks:
        - field: "service_name"
          url: "http://localhost:5601/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'fluentd-*',key:service_name,negate:!f,params:(query:'${__value.text}'),type:phrase),query:(match_phrase:(service_name:'${__value.text}')))),index:'fluentd-*',interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))"
          title: "View in Kibana" 