name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic.outputs.new_release_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          
      - name: Install dependencies
        run: npm ci
        
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
        id: semantic

  notify:
    name: Send Notification
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Send Release Notification
        if: needs.release.outputs.new_release_published == 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            🚀 Автоматический релиз v${{ needs.release.outputs.new_release_version }} создан!
            
            👤 Автор: ${{ github.actor }}
            📋 Репозиторий: ${{ github.repository }}
            
            Docker-образы будут собраны в workflow yoga-ci-cd
            
            🔍 Подробности: https://github.com/${{ github.repository }}/releases/latest
             
      - name: Send Commit Notification
        if: needs.release.outputs.new_release_published != 'true'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ℹ️ Новый коммит в ветку main не привел к релизу
            
            👤 Автор: ${{ github.actor }}
            📋 Репозиторий: ${{ github.repository }}
            💬 Сообщение коммита: ${{ github.event.head_commit.message }}
            
            🔍 Ссылка на коммит: https://github.com/${{ github.repository }}/commit/${{ github.sha }} 